language: node_js
sudo: false
node_js:
- node
- lts/*
notifications:
  email: false
  slack:
    secure: nNc3gf3fLbM8O+2CffLiGqexUTCV8c+rT2TnxMLyouXzACI0RgAUBJKlVRUxx8I4iPqRKg2D8po8pDxqpSVAtGmVrXFWBiAsYvBxedW67A+JO/Uxw5Jgy+enS1M45Uzbh7K5ZOjbXni0ufNTE8WdbqlspxslXF21lq0iwrg8/RSLLeFcCvx0Cir9km1LBZn2e9uW/kcGOZ2Q3J3EXrDCudvJ0/UwGrGoLQrSKILQjUcCugjIuOnIn5e3kPQHf5TRURMpHp7NSu/fcasK0Z6Btt+5osZJs2Z6V9WxKGFqEjhvrWd1uOv1wZTnbSrMf9ROPfViPb7sjoDb5J4LLDfquFYxivV1gkbCanpt2kGkyGZCRJu+CgJUgaqiwg+Hidb2S04efbOC+SLf/9E9v3nPXN5C5qxIznuoajyMfzjsIA/XJnvACzUVrydjnjpjh8R/hjm8/vzOzb45T7wfFjU7S/CEewVDAc2McKHPZsMOz+NpZDQ0PaPvNCBfLW9Hfh+pMGfAeh/lJNI1zx0eljlbv3Yp2neVhjiZ+V+Q0EAhVo3Ka5VmtVekQrCpFSdF1gMJR2PPLAkF14naXeWN/6VB+lmft+NaP6B5XHIUTO2AcnDVxZLgJnZtFkmxKULzVZnh+rjugBvfel40WCZZBuPMDrJ0xdIGUsMOkr+ApPpLc9g=
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
